### ISSUE TITLE
Add banner overlay for landing page

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3425]
Had the monthly NSF Crowd+AI meeting with all PIs. We are working on our accessiblecommunities.org website. As such, I'd love to build awareness for this (and other things that might arise). I'd like to consider adding a banner overlay like the "GitHub Fork Me"

Screenshot from this [codepen](https://codepen.io/fyodorio/pen/jQwEQx)
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/15f3f79b-203a-4935-bf0b-f0877944fe70)

Here's code to do so thanks to ChatGPT4:

Sure, I can help with that. Here's a simple example of how you can create an angled banner on the right side of a website using HTML and CSS. 

Sure, here's the updated HTML and CSS with the class name changed to `ps-news-ribbon`:

HTML:
```html
<a href="#" class="ps-news-ribbon" title="News on PS">News on PS</a>
```

CSS:
```css
.ps-news-ribbon {
    position: fixed;
    top: 0;
    right: 0;
    width: 200px;
    background-color: #ff7300;
    color: #fff;
    text-align: center;
    line-height: 50px;
    letter-spacing: 1px;
    transform: rotate(45deg);
    transform-origin: top right;
    text-decoration: none;
    font-family: Arial, sans-serif;
    box-shadow: 2px 2px 3px rgba(0, 0, 0, 0.5);
}
.ps-news-ribbon:hover {
    background-color: #ff3300;
}
```

You can adjust the properties as needed to fit your website's design. Remember to replace the `#` in the `href` attribute with the URL of your news page.
